#!/bin/bash
base=$(dirname $0)

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
if [ -e $HOME/.vimrc ]; then
    read -p ".vimrc exists. Overwrite? [y/N] " yn
    case $yn in
        [Yy]* )
            cp $HOME/.vimrc $HOME/vimrc.bak
            cp $base/vimrc $HOME/.vimrc && echo "Created backup $HOME/vimrc.bak"
            ;;
        * )
            echo "Aborting"
            exit 1
            ;;
    esac
else
    cp $base/vimrc $HOME/.vimrc && echo ".vimrc copied"
fi

vi +PlugInstall && echo ".vimrc is now set up with plugins."

