#!/bin/bash
base=$(dirname $0)

git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
if [ -e $HOME/.vimrc ]; then
    read -p ".vimrc exists. Overwrite? [y/N] " yn
    case $yn in
        [Yy]* )
            cp $HOME/.vimrc $HOME/vimrc.bak
            cp $base/vimrc $HOME/.vimrc && echo "Created backup $HOME/vimrc.bak"
            ;;
        * )
            echo "Aborting"
            exit 1
            ;;
    esac
else
    cp $base/vimrc $HOME/.vimrc && echo ".vimrc copied"
fi

vim +BundleInstall +qall && echo ".vimrc is now set up with vundle plugins"

