#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
    brew install reattach-to-user-namespace;
    cp -i osx-tmux.conf $HOME/.tmux.conf
else
    cp -i tmux.conf $HOME/.tmux.conf
fi

# Clone the tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
