#!/bin/sh

BASE=$(dirname $0)
RC=${1:-zshrc}
mkdir -p $HOME/.zsh
cd $HOME/.zsh
git clone git://github.com/olivierverdier/zsh-git-prompt.git git-prompt
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
cd -
if [ -e $HOME/.zshrc ]; then
    read -p ".zshrc found. Backup and overwrite? [y/N] " yn
    case $yn in
        [Yy]* )
            cp $HOME/.zshrc $HOME/zshrc.bak && cp $BASE/$RC $HOME/.zshrc
            echo "zshrc envionrment created and backup created in $HOME/zshrc.bak"
            ;;
        * ) echo "Aborting" && exit ;;
    esac
else
    cp $BASE/$RC $HOME/.zshrc && echo 'zshrc envionrment created. You can open a new zsh shell to see changes'
fi
