# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

fpath=($HOME/.zsh/zsh-completions/src $fpath)
autoload zmv
autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt correct
setopt noclobber
setopt autocd

### Aliases
alias -g L='| less'
alias -g G='| fgrep -v grep | grep'
alias -g EG='| fgrep -v grep | egrep --color'
alias ls="ls --color"
alias l='ls'
alias ll='ls -l'
alias lla='ls -la'
alias f='find . -name'
alias g='git'
alias serve="python -m http.server"
alias vi="vim"
alias git-root='cd $(git rev-parse --show-toplevel)'
alias -g tidy-json='python -m json.tool'

# Set Path
export PATH=$PATH:/usr/local/bin:$HOME/bin
GOPATH=${HOME}/go
export PATH=$PATH:$GOPATH/bin
typeset -U PATH

# Grep color
export GREP_OPTIONS="--color=auto"

# Vi mode
source "$HOME/.zsh/zsh-vim-mode/zsh-vim-mode.plugin.zsh"
# Custom virtualenv prompt
source $HOME/.zsh/virtualenv/zshrc.sh
# Git status prompt integration
source $HOME/.zsh/git-prompt/zshrc.sh
# Non git commands that affect git should change status as well
# but may be slower. Disable if git repo is too cumbersome.
export ZSH_THEME_GIT_PROMPT_NOCACHE=1

# Customized prompt
function prompt_char {
    git branch &> /dev/null && echo '±' && return
    hg root &> /dev/null && echo '☿' && return
    echo '○'
}

PROMPT='%{$fg[green]%}%n%{$reset_color%} at %{$fg[blue]%}%m%{$reset_color%} in %{$fg[yellow]%}${PWD/#$HOME/~}%{$reset_color%}
  $(prompt_char) '
RPROMPT='$(venv_prompt)$(git_super_status)'

function psgrep {
    ps xao user,pid,ppid,%cpu,%mem,start,time,command EG "(PID|$@)"
}

# Syntax highlighting on the shell
source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

function _ssh_authsock() {
    if [ -z "$TMUX" ] && [ -n "$SSH_AUTH_SOCK" ]; then
        local client="${${SSH_CLIENT%% *}//./}"
        export SSH_AUTH_SOCK_CLIENT="$HOME/.ssh/ssh-auth-sock.$client"
        ln -fns "$SSH_AUTH_SOCK" "$SSH_AUTH_SOCK_CLIENT"
    else
        export SSH_AUTH_SOCK="$SSH_AUTH_SOCK_CLIENT"
    fi
}

_ssh_authsock

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# vi mode cursor
MODE_CURSOR_VIINS="#aaeeaa blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #eeaaaa"
MODE_CURSOR_VICMD="#aaeeaa block"
MODE_CURSOR_SEARCH="#eeaaee steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #aaeeee"
